### ISSUE TITLE
Adding genesis presets

### ISSUE THREAD

**Issue by CrackTheCode016** [paritytech/polkadot-sdk-parachain-template#19]
I understand that this template is kept in sync with the current template, but given that the `frame-omni-bencher` currently relies on there being presets, we should include them so as to allow/encourage the usage of this tool: https://github.com/paritytech/polkadot-sdk/blob/master/templates/parachain/runtime/src/genesis_config_presets.rs

**Comment by iulianbarbu** [comment]
Hi @CrackTheCode016 ! I am not very familiar with the `frame-omni-bencher` usage yet, but what I can tell you is that we're wrapping up with a some polishing work related to [Omni Node](https://paritytech.github.io/polkadot-sdk/master/polkadot_sdk_docs/reference_docs/omni_node/index.html) that touches the parachain template, and once that's over we will cut off a release. Part of it should be syncing the "upstream" changes with this repo too. We're aiming to have it done next week.

Lets keep this issue open and we can update/close it by next week based on how the work unfolds.

**Comment by iulianbarbu** [comment]
Hey @CrackTheCode016 , the parachain template repo was synced with stable2409, which contains the genesis config presets in the runtime. There are some more docs related updates that will be released with stable2412 in December, but they shouldn't change much of what's currently latest on master.

Will close this issue for now but feel free to reopen it if the latest sync doesn't address what you were looking for.
